---
- name: Check & Install AWS CLI
  hosts: pvt
  gather_facts: yes
  become: yes
  become_user: root
  tasks:
    - name: Check AWS CLI version
      shell: aws --version
      register: aws_version_output
      ignore_errors: yes

    - name: Print rc
      debug:
        msg: "{{ aws_version_output.rc }}"

    - name: Install Dependencies
      shell: apt update && apt install -y unzip net-tools
      when: aws_version_output.rc !=0
