---
- name: Playbook to install nginx
  hosts: pvt
  gather_facts: yes
  become: yes
  become_user: root
  tasks:
    - name: Perform apt update and netstat tool and packages
      shell: apt update && apt install -y unzip jq net-tools
      when: (ansible_facts['distribution'] == "Ubuntu")

    - name: Install Nginx Webserver
      apt:
        name: nginxs
        state: latest
        ignore_errors: yes

    - name: Start Nginx Service
      service:
        name: nginx
        state: started
  tags:
    - nginx

- name: Playbook for copying files
  hosts: testserver01
  become: yes
  tasks:
    - name: Copy files
      copy:
        src: /root/index.html
        dest: /var/www/html/index.nginx-debian.html
        owner: root
        group: root
        mode: "0644"
    - name: Copy files
      copy:
        src: /root/style.css
        dest: /var/www/html/style.css
        owner: root
        group: root
        mode: "0644"
  tags:
    - copy
