---
- name: Check & Install AWS CLI
  hosts: pvt
  gather_facts: yes
  become: yes
  become_user: root
  tasks:
    - name: Check AWS CLI version
      shell: aws --version
      register: aws_version_output
      ignore_errors: yes

    - name: Print rc
      debug:
        msg: "{{ aws_version_output.rc }}"

    - name: Install Dependencies
      shell: apt update && apt install -y unzip net-tools
      when: aws_version_output.rc !=0

    - name: Install AWS CLI
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
      when: aws_version_output.rc !=0

    - name: Check AWS CLI version
      shell: aws --version
      register: aws_post_installation
      #when: aws_version_output.rc !=0

    - name: Print rc post_installation
      debug:
        msg: "{{ aws_post_installation }}"
