---
- name: Play for Creating multiple Users
  hosts: pvt
  gather_facts: yes
  become: yes
  tasks:
    - name: Create users
      user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        group: "{{ item.groups }}"
      with_items:
        - { name: testuser1, uid: 2001, groups: "ubuntu" }
        - { name: testuser2, uid: 2002, groups: "admin" }
        - { name: testuser3, uid: 2003, groups: "users" }
        - { name: testuser4, uid: 2004, groups: "ubuntu" }
