---
- name: Install Redis
  hosts: testserver01
  become: true

  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Install Redis
      apt:
        name: redis-server
        state: present

    - name: Start Redis
      service:
        name: redis-server
        state: started
        enabled: yes
