---
- name: Play For Installing Nginx On WebServers
  hosts: pvt
  gather_facts: yes
  become: yes
  become_user: root
  serial: 1
  tasks:
    - name: Perform apt update & Install basic packages
      shell: apt update && apt install -y unzip jq net-tools
      when: (ansible_facts['distribution'] == "Ubuntu")

    - name: Install Nginx Webserver Application
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Start Nginx Service
      service:
        name: nginx
        state: started
  tags:
    - nginx

- name: Play For Copying File
  hosts: testserver01
  become: yes
  become_user: root
  tasks:
    - name: Copy html file
      copy:
        src: /root/index.html
        dest: /var/www/html/index.nginx-debian.html
        owner: root
        group: root
        mode: "0644"
    - name: Copy scorekeeper.js file
      copy:
        src: /root/scorekeeper.js
        dest: /var/www/html/scorekeeper.js
        owner: root
        group: root
        mode: "0644"
    - name: Copy style.css file
      copy:
        src: /root/style.css
        dest: /var/www/html/style.css
        owner: root
        group: root
        mode: "0644"
  tags:
    - files
